### ISSUE TITLE
Google Gemini support

### ISSUE THREAD

**Issue by aurelg** [efugier/smartcat#50]
Thanks for this awesome tool!

Gemini models are pretty good, and Google offers a generous free tier. Would it be possible to add support for their API?

**Comment by a1v0lut10n** [comment]
@aurelg for what it's worth, I got Google's gemini's models to work in this fork a while back: https://github.com/a1v0lut10n/smartcat-gemini in this PR: https://github.com/a1v0lut10n/smartcat-gemini/pull/1. Was in a rush to try gemini's larger context windows with smartcat, and I did not get around to try and turn this into a contribution. But perhaps it is useful towards having Gemini support.

**Comment by efugier** [comment]
Hey @a1v0lut10n I already had noticed your work, and I cease this opportunity to say I would love for you to open a PR on this repo 😁

**Comment by efugier** [comment]
@aurelg I'd love smartcat to become gemini-compatible, I'm just a bit short on time atm, super open to contribs!

**Comment by a1v0lut10n** [comment]
@efugier I'd be happy to create a PR adding gemini support.

**Comment by gnur** [comment]
For others reading this, the gemini api is compatible with the openai api, so this just works:

```toml
[openai]
url = "https://generativelanguage.googleapis.com/v1beta/chat/completions"
default_model = "gemini-2.0-flash"
api_key = ""
```
