### ISSUE TITLE
[Feature Request] Enable Configuration File Splitting

### ISSUE THREAD

**Issue by s3igo** [efugier/smartcat#53]
Thank you for the excellent tool!

In my use case, the `prompts.toml` file has grown too large, making it difficult to maintain. I would appreciate if you could implement the ability to split files.

Referring to the README sample, I'm envisioning something like this:

`~/.config/smartcat/prompts.toml`

```toml
includes = ["./snippets/test.toml"] # Specify files to include

[default]
api = "ollama"
model = "phi3"

[[default.messages]]
role = "system"
content = """\
You are an expert programmer and a shell master. You value code efficiency and clarity above all things. \
What you write will be piped in and out of cli programs so you do not explain anything unless explicitely asked to. \
Never write ``` around your answer, provide only the result of the task you are given. Preserve input formatting.\
"""

[empty]
api = "openai"
messages = []
```

`~/.config/smartcat/snippets/test.toml`

```toml
[test]
api = "anthropic"
temperature = 0.0

[[test.messages]]
role = "system"
content = """\
You are an expert programmer and a shell master. You value code efficiency and clarity above all things. \
What you write will be piped in and out of cli programs so you do not explain anything unless explicitely asked to. \
Never write ``` around your answer, provide only the result of the task you are given. Preserve input formatting.\
"""

[[test.messages]]
role = "user"
content ='''Write tests using pytest for the following code. Parametrize it if appropriate.

#[<input>]
'''
```
